from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT = REPO_ROOT / "scripts" / "actionability_check.py"


GOOD_INSTRUCTION = """\
## What's wrong
Running `python3 /app/environment/tools/reconcile.py --profile strict --mode audit`
currently produces a report whose drift and digest records do not match the
input trace.

## What to change
Fix the source code under `/app/environment` so the normal reconciliation
pipeline regenerates the report. Static or manual generated-output writes are
insufficient because the verifier deletes and regenerates the artifact.

## Where to look
Start in the `/app/environment/tools` and `/app/environment/lib`
reconciliation components.

## What the verifier checks
The verifier reruns `python3 /app/environment/tools/reconcile.py --profile
strict --mode audit`. It checks the `items` array has 3 records and each
record exposes `profile`, `mode`, `drift`, `digest`, and `algorithm`. The
public formula is `drift = observed - baseline`; the numeric tolerance is
1e-6. The digest algorithm is sha256 and the digest text has length 64.

## What is not sufficient
Static output writes, test edits, bypassing the pipeline, and only changing a
driver wrapper are not sufficient.

## Repro
Run `python3 /app/environment/tools/reconcile.py --profile strict --mode audit`
and inspect `/app/output/report.json`.
"""

CONCISE_PARAGRAPH_INSTRUCTION = """\
The reconciliation report generated by `/app/environment/tools/reconcile.py`
does not match the input trace: its drift and digest records are stale for the
strict audit profile.

From `/app`, run `python3 /app/environment/tools/reconcile.py --profile strict
--mode audit` to regenerate `/app/output/report.json`. Repair the source code
under `/app/environment`, especially the tools and lib reconciliation pipeline;
static or manual generated-output writes are insufficient because the verifier
deletes and regenerates the artifact.

The JSON report has an `items` array with 3 records. Each record exposes
`profile`, `mode`, `drift`, `digest`, and `algorithm`. The public formula is
`drift = observed - baseline`, the numeric tolerance is 1e-6, the digest
algorithm is sha256, and digest text has length 64. Do not edit tests, bypass
the pipeline, or solve this only by changing a driver wrapper.
"""

REQUIREMENTS_STYLE_INSTRUCTION = """\
# Reconciliation Audit Report

Build the source behavior for `/app/environment/tools/reconcile.py` so the
strict audit report is regenerated from the input trace instead of stale state.
Run `python3 /app/environment/tools/reconcile.py --profile strict --mode audit`
from `/app`; it writes `/app/output/report.json`.

## Requirements

- Fix source code under `/app/environment`, with the relevant starting scope in
  the tools/lib reconciliation pipeline.
- Static or manual output writes are insufficient because the verifier deletes
  and regenerates `/app/output/report.json`.
- The report is a JSON object with an `items` array containing 3 records.
- Each item has `profile`, `mode`, `drift`, `digest`, and `algorithm`.
- Use the public formula `drift = observed - baseline`, tolerance 1e-6,
  sha256 digests, and 64-character digest text.
- Do not edit tests, bypass the pipeline, or solve the task by changing only a
  driver wrapper.
"""

OUTPUT_CONTRACT = """\
user_visible_outputs = ["/app/output/report.json"]
internal_harness_files = []

[structured_outputs.report]
target = "/app/output/report.json"
format = "json"
instruction_checks = ["items", "profile", "mode", "drift", "digest", "algorithm"]
"""

TEST_OUTPUTS = """\
import json
import math
import subprocess
from pathlib import Path

OUTPUT = Path("/app/output/report.json")


def test_report_is_regenerated_from_source():
    OUTPUT.unlink(missing_ok=True)
    subprocess.run(
        [
            "python3",
            "/app/environment/tools/reconcile.py",
            "--profile",
            "strict",
            "--mode",
            "audit",
        ],
        check=True,
    )
    data = json.loads(OUTPUT.read_text())
    assert len(data["items"]) == 3
    row = data["items"][0]
    assert row["profile"] == "strict"
    assert row["mode"] == "audit"
    assert math.isclose(row["drift"], 1.5, abs_tol=1e-6)
    assert len(row["digest"]) == 64
    assert row["algorithm"] == "sha256"
"""


class ActionabilityCheckTests(unittest.TestCase):
    def make_task(
        self,
        tmp: Path,
        *,
        instruction: str = GOOD_INSTRUCTION,
        tests: str = TEST_OUTPUTS,
        output_contract: str = OUTPUT_CONTRACT,
    ) -> Path:
        task_dir = tmp / "tasks" / "demo-actionability"
        (task_dir / "tests").mkdir(parents=True)
        (task_dir / "environment" / "tools").mkdir(parents=True)
        (task_dir / "environment" / "lib").mkdir(parents=True)
        (task_dir / "instruction.md").write_text(instruction)
        (task_dir / "output_contract.toml").write_text(output_contract)
        (task_dir / "tests" / "test_outputs.py").write_text(tests)
        (task_dir / "tests" / "test.sh").write_text("python3 -m pytest /app/tests/test_outputs.py\n")
        return task_dir

    def run_checker(self, task_dir: Path, *args: str) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [sys.executable, str(SCRIPT), str(task_dir), *args],
            cwd=REPO_ROOT,
            check=False,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )

    def test_json_passes_actionable_instruction(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            task_dir = self.make_task(Path(tmp))
            result = self.run_checker(task_dir, "--json")

        self.assertEqual(result.returncode, 0, result.stderr + result.stdout)
        payload = json.loads(result.stdout)
        self.assertEqual(payload["status"], "PASS")
        self.assertEqual(payload["summary"]["fail"], 0)
        self.assertEqual(payload["summary"]["warn"], 0)

    def test_concise_paragraph_instruction_passes_without_template_headings(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            task_dir = self.make_task(Path(tmp), instruction=CONCISE_PARAGRAPH_INSTRUCTION)
            result = self.run_checker(task_dir, "--json", "--strict")

        self.assertEqual(result.returncode, 0, result.stderr + result.stdout)
        payload = json.loads(result.stdout)
        self.assertEqual(payload["status"], "PASS")

    def test_title_requirements_instruction_passes_without_template_headings(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            task_dir = self.make_task(Path(tmp), instruction=REQUIREMENTS_STYLE_INSTRUCTION)
            result = self.run_checker(task_dir, "--json", "--strict")

        self.assertEqual(result.returncode, 0, result.stderr + result.stdout)
        payload = json.loads(result.stdout)
        self.assertEqual(payload["status"], "PASS")

    def test_six_heading_template_is_allowed_but_not_required(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            template_task = self.make_task(Path(tmp) / "template", instruction=GOOD_INSTRUCTION)
            natural_task = self.make_task(Path(tmp) / "natural", instruction=CONCISE_PARAGRAPH_INSTRUCTION)
            template_result = self.run_checker(template_task, "--json", "--strict")
            natural_result = self.run_checker(natural_task, "--json", "--strict")

        self.assertEqual(template_result.returncode, 0, template_result.stdout)
        self.assertEqual(natural_result.returncode, 0, natural_result.stdout)

    def test_missing_source_fix_intent_fails_when_tests_rerun_source(self) -> None:
        instruction = GOOD_INSTRUCTION.replace(
            "Fix the source code under `/app/environment` so the normal reconciliation\n"
            "pipeline regenerates the report. ",
            "Update the report so the correct artifact exists. ",
        )
        with tempfile.TemporaryDirectory() as tmp:
            task_dir = self.make_task(Path(tmp), instruction=instruction)
            result = self.run_checker(task_dir, "--json")

        self.assertNotEqual(result.returncode, 0)
        payload = json.loads(result.stdout)
        check = next(item for item in payload["checks"] if item["id"] == "source_fix_intent")
        self.assertEqual(check["severity"], "FAIL")
        self.assertIn("source code under /app/environment", check["message"])

    def test_missing_static_output_warning_fails_when_tests_regenerate_outputs(self) -> None:
        instruction = GOOD_INSTRUCTION.replace(
            "Static or manual generated-output writes are\n"
            "insufficient because the verifier deletes and regenerates the artifact.\n",
            "",
        ).replace(
            "Static output writes, ",
            "",
        )
        with tempfile.TemporaryDirectory() as tmp:
            task_dir = self.make_task(Path(tmp), instruction=instruction)
            result = self.run_checker(task_dir, "--json")

        self.assertNotEqual(result.returncode, 0)
        payload = json.loads(result.stdout)
        check = next(item for item in payload["checks"] if item["id"] == "regenerated_vs_static_output")
        self.assertEqual(check["severity"], "FAIL")

    def test_missing_verifier_command_fails(self) -> None:
        instruction = GOOD_INSTRUCTION
        for old, new in [
            ("Running `python3 /app/environment/tools/reconcile.py --profile strict --mode audit`\n", "Running the reconciliation workflow\n"),
            ("The verifier reruns `python3 /app/environment/tools/reconcile.py --profile\nstrict --mode audit`. ", "The verifier reruns the reconciliation workflow. "),
            ("Run `python3 /app/environment/tools/reconcile.py --profile strict --mode audit`\n", "Run the reconciliation workflow\n"),
            ("`profile`, `mode`, ", ""),
        ]:
            instruction = instruction.replace(old, new)

        with tempfile.TemporaryDirectory() as tmp:
            task_dir = self.make_task(Path(tmp), instruction=instruction)
            result = self.run_checker(task_dir, "--json")

        self.assertNotEqual(result.returncode, 0)
        payload = json.loads(result.stdout)
        check = next(item for item in payload["checks"] if item["id"] == "verifier_command_pipeline")
        self.assertEqual(check["severity"], "FAIL")
        self.assertIn("reconcile.py", check["message"])

    def test_hidden_profile_flag_fails(self) -> None:
        instruction = GOOD_INSTRUCTION.replace("--profile strict --mode audit", "--mode audit")
        instruction = instruction.replace("--profile\nstrict --mode audit", "--mode audit")
        instruction = instruction.replace("`profile`, ", "")
        with tempfile.TemporaryDirectory() as tmp:
            task_dir = self.make_task(Path(tmp), instruction=instruction)
            result = self.run_checker(task_dir, "--json")

        self.assertNotEqual(result.returncode, 0)
        payload = json.loads(result.stdout)
        check = next(item for item in payload["checks"] if item["id"] == "inputs_profiles_argument_splits")
        self.assertEqual(check["severity"], "FAIL")
        self.assertIn("--profile", check["message"])

    def test_direct_library_call_requires_library_level_contract(self) -> None:
        tests = """\
import sys

sys.path.insert(0, "/app/environment/lib")
from reconciler import build_report


def test_build_report_direct_call():
    row = build_report(profile="strict", mode="audit")["items"][0]
    assert row["profile"] == "strict"
"""
        instruction = GOOD_INSTRUCTION.replace(
            " and only changing a\n"
            "driver wrapper are not sufficient",
            " are not sufficient",
        )
        instruction = instruction.replace("components.", "components.")
        instruction = instruction.replace("driver wrapper", "wrapper")
        instruction = instruction.replace("pipeline regenerates", "pipeline and module-level behavior regenerate")
        with tempfile.TemporaryDirectory() as tmp:
            task_dir = self.make_task(Path(tmp), instruction=instruction, tests=tests)
            result = self.run_checker(task_dir, "--json")

        self.assertEqual(result.returncode, 0, result.stdout)

        missing_library_instruction = instruction.replace(" and module-level behavior", "")
        with tempfile.TemporaryDirectory() as tmp:
            task_dir = self.make_task(Path(tmp), instruction=missing_library_instruction, tests=tests)
            result = self.run_checker(task_dir, "--json")

        self.assertNotEqual(result.returncode, 0)
        payload = json.loads(result.stdout)
        check = next(item for item in payload["checks"] if item["id"] == "direct_library_call_expectations")
        self.assertEqual(check["severity"], "FAIL")

    def test_strict_upgrades_missing_subsystem_scope_warning(self) -> None:
        instruction = GOOD_INSTRUCTION.replace(
            "Start in the `/app/environment/tools` and `/app/environment/lib`\n"
            "reconciliation components.",
            "Start around the durable frontier.",
        )
        with tempfile.TemporaryDirectory() as tmp:
            task_dir = self.make_task(Path(tmp), instruction=instruction)
            default_result = self.run_checker(task_dir, "--json")
            strict_result = self.run_checker(task_dir, "--json", "--strict")

        default_payload = json.loads(default_result.stdout)
        self.assertEqual(default_payload["status"], "WARN")
        strict_payload = json.loads(strict_result.stdout)
        scope = next(item for item in strict_payload["checks"] if item["id"] == "subsystem_entry_point")
        self.assertEqual(scope["severity"], "FAIL")

    def test_metaphor_only_requirement_warns(self) -> None:
        instruction = GOOD_INSTRUCTION.replace(
            "currently produces a report whose drift and digest records do not match the\n"
            "input trace.",
            "currently produces a report whose durable frontier records do not match the\n"
            "input trace. Make it robust and handle properly.",
        ).replace(
            "The verifier reruns",
            "The verifier reruns",
        )
        with tempfile.TemporaryDirectory() as tmp:
            task_dir = self.make_task(Path(tmp), instruction=instruction)
            result = self.run_checker(task_dir, "--json")

        payload = json.loads(result.stdout)
        check = next(item for item in payload["checks"] if item["id"] == "metaphor_only_requirements")
        self.assertEqual(check["severity"], "WARN")
        self.assertIn("durable frontier", check["message"])


if __name__ == "__main__":
    unittest.main()
